#!/bin/sh

# eza alias
if command -v eza > /dev/null 2>&1; then
  alias ls='eza --icons=auto'
fi

# ls aliases
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'

# cat alias
if command -v bat > /dev/null 2>&1; then
  alias cat='bat'
fi

if command -v z > /dev/null 2>&1; then
  alias cd='z'
fi
