#!/bin/sh
export PF_INFO="ascii title os host kernel uptime pkgs wm memory palette"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="${XDG_CONFIG_HOME}/x11/xinitrc"
export GOPATH="${XDG_DATA_HOME}/go"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc-2.0"
export WGETRC="${XDG_CONFIG_HOME}/wget/wgetrc"
export HISTFILE="${XDG_DATA_HOME}/history"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"
export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export ANDROID_SDK_HOME="${XDG_CONFIG_HOME}/android"
export BUN_INSTALL="${XDG_DATA_HOME}/bun"

export W3M_DIR="${XDG_CONFIG_HOME}/w3m"

export PATH="$HOME/.local/bin:$CARGO_HOME/bin:$PATH"
