local layout_path = require("gears").filesystem.get_themes_dir() .. "default/layouts/"

theme.layout_dwindle        = layout_path .. "dwindlew.png"
theme.layout_fairh          = layout_path .. "fairhw.png"
theme.layout_fairv          = layout_path .. "fairvw.png"
theme.layout_floating       = layout_path .. "floatingw.png"
theme.layout_magnifier      = layout_path .. "magnifierw.png"
theme.layout_max            = layout_path .. "maxw.png"
theme.layout_spiral         = layout_path .. "spiralw.png"
theme.layout_tilebottom     = layout_path .. "tilebottomw.png"
theme.layout_tileleft       = layout_path .. "tileleftw.png"
theme.layout_tile           = layout_path .. "tilew.png"
theme.layout_tiletop        = layout_path .. "tiletopw.png"

theme.layout_fullscreen     = layout_path .. "fullscreenw.png"
theme.layout_cornernw       = layout_path .. "cornernww.png"
theme.layout_cornerne       = layout_path .. "cornernew.png"
theme.layout_cornersw       = layout_path .. "cornersww.png"
theme.layout_cornerse       = layout_path .. "cornersew.png"
