local M = {}

M.devIcons = {
	File				  = " ",
	Module 	  	  = " ",
	Namespace 	  = " ",
	Package	  	  = " ",
	Class		  	  = " ",
	Method				= " ",
	Property      = " ",
	Field         = " ",
	Constructor	  = " ",
	Enum				  = " ",
	EnumMember    = " ",
	Interface		  = " ",
	Function		  = "󰊕 ",
	Variable		  = " ",
	Constant		  = " ",
	String			  = " ",
	Number			  = " ",
	Boolean			  = " ",
	Array				  = " ",
	Object			  = " ",
	Key					  =	" ",
	Null				  = "󰟢 ",
	Struct			  = " ",
	Event         = " ",
	Operator			= " ",
	TypeParameter = " ",
}

M.kind_icons = {
	Text = "󰉿",
	Copilot = "",
	Method = "",
	Function = "󰊕",
	Constructor = "",
	Field = "",
	Variable = "",
	Class = "",
	Array = "",
	Interface = "",
	Module = "",
	Property = "",
	Unit = "",
	Value = "󰎠",
	Enum = "",
	Keyword = "",
	Snippet = "",
	Color = "",
	File = "",
	Reference = "",
	Folder = "",
	EnumMember = "",
	Constant = "",
	Struct = "",
	Event = "",
	Operator = "",
	TypeParameter = "",
} 

return M
