# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
  # Smart-enter
  { on = "l", run = "plugin augment-command enter", desc = "Enter a directory and skip directories with only a single subdirectory" },

  # Shell
  { on = "$", run = "shell --block --confirm $SHELL", desc = "Open shell" },

  # Utils
  { on = "<C-d>", run = "plugin drag", desc = "Drag files" },
  { on = "T", run = "plugin --sync max-preview", desc = "Maximize or restore preview" },
  { on = "M", run = "plugin mount", desc = "Mount manager" },
]

[tasks]

prepend_keymap = []

[input]

prepend_keymap = []

[help]

prepend_keymap = []
