# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  # Smart-enter
  { on = "l", run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },

  # Utils
  { on = "<C-d>", run = '''shell --confirm 'export IFS=";;"; ripdrag -ax $(echo "$@" | sed "s/ \//;;\//g")'''', desc = "Drag files" },
  { on = "<C-e>", run = '''shell --confirm 'export IFS=";;"; atool -x $(echo "$@" | sed "s/ \//;;\//g")'''', desc = "Extract" },
  { on = "T", run = "plugin --sync max-preview", desc = "Maximize or restore preview" }
]

[tasks]

prepend_keymap = []

[select]

prepend_keymap = []

[input]

prepend_keymap = []

[completion]

prepend_keymap = []

[help]

prepend_keymap = []
