# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# vim:fileencoding=utf-8:foldmethod=marker

# : Flavor {{{

[flavor]
use = ""

# : }}}

# : Manager {{{

[manager]
cwd = { fg = "cyan" }

# Hovered
hovered = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "yellow", bold = true, italic = true, underline = true }
find_position = { fg = "magenta", bg = "reset", bold = true, italic = true }

# Marker
marker_copied = { fg = "lightgreen", bg = "lightgreen" }
marker_cut = { fg = "lightred", bg = "lightred" }
marker_marked = { fg = "lightcyan", bg = "lightcyan" }
marker_selected = { fg = "lightyellow", bg = "lightyellow" }

# Tab
tab_active = { reversed = true }
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "white", bg = "green" }
count_cut = { fg = "white", bg = "red" }
count_selected = { fg = "white", bg = "yellow" }

# Border
border_symbol = "│"
border_style = { fg = "gray" }

# Highlighting
syntect_theme = ""

# : }}}


# : Status {{{

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "gray", bg = "gray" }

# Mode
mode_normal = { bg = "blue", bold = true }
mode_select = { bg = "red", bold = true }
mode_unset = { bg = "red", bold = true }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "blue", bg = "black" }
progress_error = { fg = "red", bg = "black" }

# Permissions
permissions_t = { fg = "green" }
permissions_r = { fg = "yellow" }
permissions_w = { fg = "red" }
permissions_x = { fg = "cyan" }
permissions_s = { fg = "darkgray" }

# : }}}


# : Select {{{

[select]
border = { fg = "blue" }
active = { fg = "magenta", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border = { fg = "blue" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[completion]
border = { fg = "blue" }
active = { reversed = true }
inactive = {}

# Icons
icon_file = ""
icon_folder = ""
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border = { fg = "blue" }
title = {}
hovered = { fg = "magenta", underline = true }

# : }}}


# : Which {{{

[which]
cols = 3
mask = { bg = "black" }
cand = { fg = "lightcyan" }
rest = { fg = "darkgray" }
desc = { fg = "lightmagenta" }
separator = "  "
separator_style = { fg = "darkgray" }

# : }}}


# : Help {{{

[help]
on = { fg = "cyan" }
run = { fg = "magenta" }
desc = {}
hovered = { reversed = true, bold = true }
footer = { fg = "black", bg = "white" }

# : }}}


# : Notify {{{

[notify]
title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "cyan" },

  # Media
  { mime = "{audio,video}/*", fg = "yellow" },

  # Archives
  { mime = "application/*zip", fg = "magenta" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "magenta" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "green" },

  # Fallback
  # { name = "*", fg = "white" },
  { name = "*/", fg = "blue" },
]

[icon]
prepend_rules = [
  # Text
  { name = "*.org", text = "", fg = "#77aa99" },

  # Named files
  { name = "*COPYING", text = "󰿃", fg = "#cbcb41" },
  { name = "*Containerfile", text = "󰡨", fg = "#458ee6" },
  { name = "*Dockerfile", text = "󰡨", fg = "#458ee6" },
  { name = "*LICENSE", text = "󰿃", fg = "#d0bf41" },

  # xdg-dirs
  { name = "*Área De Trabalho/", text = "" },
  { name = "*Development/", text = "" },
  { name = "*Documentos/", text = "" },
  { name = "*Downloads/", text = "" },
  { name = "*Musicas/", text = "" },
  { name = "*Imagens/", text = "" },
  { name = "*Público/", text = "" },
  { name = "*Vídeos/", text = "" },
]

# : }}}
